sudo: required
services:
  - docker

before_install:
  - docker build -t monkeyd/react-tests -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true monkeyd/react-tests npm run test

after_success:
  # Build images
  - docker build -t monkeyd/multi-frontend ./frontend
  - docker build -t monkeyd/multi-nginx ./nginx
  - docker build -t monkeyd/multi-server ./server
  - docker build -t monkeyd/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push monkeyd/multi-frontend
  - docker push monkeyd/multi-nginx
  - docker push monkeyd/multi-server
  - docker push monkeyd/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-766770920205"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"