sudo: required
services:
  - docker

before_install:
  - docker build -t monkeyd/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true monkeyd/react-tests npm run test

after_success:
  - docker build -t monkeyd/multi-client ./client
  - docker build -t monkeyd/multi-nginx ./nginx
  - docker build -t monkeyd/multi-server ./server
  - docker build -t monkeyd/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push monkeyd/multi-client
  - docker push monkeyd/multi-nginx
  - docker push monkeyd/multi-client
  - docker push monkeyd/multi-worker